<a href="https://colab.research.google.com/github/aliansgp/Learning-PyTorch/blob/main/CodeMe-com/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
my_list = [[1,2,3],
           [4,5,6],
           [7,8,9]]

In [3]:
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np_list = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
np_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np_rand = np.random.rand(3,4)
np_randint = np.random.randint(0,5,(4,3))

In [20]:
# this is 3 by 4 matrix (just entered shape of npArray in random.rand and values are between 0 to 1.)
np_rand

array([[0.75708945, 0.65762478, 0.86818264, 0.4797509 ],
       [0.22092058, 0.30355511, 0.20206777, 0.84294186],
       [0.18040259, 0.69044856, 0.70588698, 0.8541543 ]])

In [21]:
np_rand.dtype

dtype('float64')

In [18]:
# this is diffrent, low and high number must be configured and shape must be a tuple
np_randint

array([[0, 2, 0],
       [3, 0, 4],
       [2, 1, 3],
       [4, 2, 0]])

In [22]:
tensor_2d = torch.rand(3,4)
tensor_2d_int = torch.randint(0,5,(4,3))

In [25]:
# just like np
tensor_2d

tensor([[0.0222, 0.4151, 0.1779, 0.0783],
        [0.5836, 0.6677, 0.9678, 0.9420],
        [0.2872, 0.9561, 0.4862, 0.0708]])

In [26]:
# just like np
tensor_2d_int

tensor([[0, 0, 3],
        [1, 3, 0],
        [2, 1, 3],
        [3, 4, 3]])

In [28]:
# convert npArray into tensor
# type is similar with np
# default of tensors is float32 not 64
np2tensor = torch.tensor(np_rand)
np2tensor

tensor([[0.7571, 0.6576, 0.8682, 0.4798],
        [0.2209, 0.3036, 0.2021, 0.8429],
        [0.1804, 0.6904, 0.7059, 0.8542]], dtype=torch.float64)