<a href="https://colab.research.google.com/github/aliansgp/Learning-PyTorch/blob/main/CodeMe-com/02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [16]:
range_tensor = torch.arange(10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# reshape
reshape_range = range_tensor.reshape(2,5)
reshape_range

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# reshape if we dont know number of items:
reshape_range = range_tensor.reshape(5,-1)
reshape_range

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [8]:
# most be divided
reshape_range = range_tensor.reshape(6,-1)
reshape_range

RuntimeError: ignored

In [10]:
# view
view_range = range_tensor.view(5,-1)
view_range

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
view_range = range_tensor.view(2,5)
view_range

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# reshape and view will update if main change:
changed_tensor = range_tensor
changed_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
changed_view = changed_tensor.view(2,5)
changed_view

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
changed_tensor[1] = 1234
# changed_view will change without defining again:
changed_view

tensor([[   0, 1234,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [22]:
# also range_tensor changed!!!
# we only changed changed_tensor...
# all of this definitions are linked.
range_tensor

tensor([   0, 1234,    2,    3,    4,    5,    6,    7,    8,    9])

In [23]:
# Slicing
range_tensor[1:4]

tensor([1234,    2,    3])

In [27]:
# Calling a number with index will not return ,number,
# it will return scaled number in tensor type
# but we can use math operation
range_tensor[1] + 1

tensor(1235)

In [31]:
# grab a column of a tensor
view_range = view_range.view(5,2)
view_range

tensor([[   0, 1234],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [33]:
# return a column items
view_range[:,1]

tensor([1234,    3,    5,    7,    9])

In [34]:
# return column as column:
view_range[:,1:]

tensor([[1234],
        [   3],
        [   5],
        [   7],
        [   9]])