<a href="https://colab.research.google.com/github/aliansgp/Learning-PyTorch/blob/main/CodeMe-com/03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Math Functions

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# addition with torch
torch.add(tensor_a ,tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
# subtraction with torch
torch.sub(tensor_a , tensor_b)

tensor([-4, -4, -4, -4])

In [9]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
# multiplication with torch
torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
# multiplication with torch smaller version
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
# Division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [14]:
# division with torch
torch.divide(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [15]:
# division with torch smaller version
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [17]:
# Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
# remainder with torch
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [21]:
# Power with torch
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

### also for each tensor, there is a function for math

In [24]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a.div(tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [26]:
tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [27]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

## reassignment


In [30]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [33]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
# so tensor_ a did not change
tensor_a

tensor([1, 2, 3, 4])

In [36]:
# if we use ' _ ' for functions, result will replace:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
# now it changed
tensor_a

tensor([ 6,  8, 10, 12])